---
- name: Creat Vlan by Ansible
  hosts: AS1
  gather_facts: no

  tasks:
    - name: Show Vlan
      ios_command:
        commands:
          - show vlan brief
      register: output

    - name: Tao Vlan
      ios_vlan:
        aggregate:
        - { vlan_id: 10, name: IT, interfaces: [Ethernet1/0, Ethernet1/1], delay: 15, state: suspend }
        - { vlan_id: 20, name: KeToan, interfaces: [Ethernet2/0, Ethernet2/1], state: present }
        - { vlan_id: 30, name: Guest, interfaces: [Ethernet3/0, Ethernet3/1], state: present }
       
    - name: Merge provided configuration with device configuration
      ios_l2_interfaces:
        config:
          - name: Ethernet0/1-3
            trunk:
              allowed_vlan: all
              pruning_vlan: all
              encapsulation: dot1q
        state: merged
    - debug: var=output.stdout
