---
- name: Show Ip Interfaces
  hosts: AS
  gather_facts: no

  tasks:
    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: output

    - debug: var=output.stdout
